package pAccueil;

/**
 *
 * @author maxim
 */
public class pAPropos extends javax.swing.JPanel {

    /**
     * Creates new form pAccueil
     */
    public pAPropos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tTextAPropos = new javax.swing.JLabel();
        tTextAPropos1 = new javax.swing.JLabel();
        tTextAPropos2 = new javax.swing.JLabel();
        tTextAPropos3 = new javax.swing.JLabel();
        pAccueil = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1300, 700));
        setMinimumSize(new java.awt.Dimension(1300, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 70)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("A Propos");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 140));

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Maxime INNOCENTI & Antoine HENRIET");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 1300, 120));

        tTextAPropos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tTextAPropos.setForeground(new java.awt.Color(255, 255, 255));
        tTextAPropos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tTextAPropos.setText("Projet JAVA 2A EPF");
        add(tTextAPropos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, 200, 50));

        tTextAPropos1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tTextAPropos1.setForeground(new java.awt.Color(255, 255, 255));
        tTextAPropos1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tTextAPropos1.setText("Sujet : Simulation Feu de Foret");
        add(tTextAPropos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 490, 310, 50));

        tTextAPropos2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tTextAPropos2.setForeground(new java.awt.Color(255, 255, 255));
        tTextAPropos2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tTextAPropos2.setText("Développé avec l'environnement NetBeans");
        add(tTextAPropos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 360, 320, 50));

        tTextAPropos3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tTextAPropos3.setForeground(new java.awt.Color(255, 255, 255));
        tTextAPropos3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tTextAPropos3.setText("Programme développé avec JDK 16");
        add(tTextAPropos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 320, 50));

        pAccueil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pAccueil/Foret nv.png"))); // NOI18N
        pAccueil.setPreferredSize(new java.awt.Dimension(1300, 730));
        add(pAccueil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 700));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel pAccueil;
    private javax.swing.JLabel tTextAPropos;
    private javax.swing.JLabel tTextAPropos1;
    private javax.swing.JLabel tTextAPropos2;
    private javax.swing.JLabel tTextAPropos3;
    // End of variables declaration//GEN-END:variables
}
