/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dessin;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javax.swing.ButtonGroup;
import javax.swing.JLabel;
import pComponents.button.MyButton;
import pComponents.radio_button.RadioButtonCustom;
import pComponents.slider_material.JsliderCustom_Epaisseur;

/**
 *
 * @author Think
 */
public class pPalette extends javax.swing.JPanel {

    /**
     * Creates new form pParametreTerrain
     */
    public pPalette() {
        initComponents();
        
        lEpaisseur.setVisible(false);
        scEpaisseur.setVisible(false);

        lPinceau.setVisible(false);
        rbcPrairiePinceau.setVisible(false);
        rbcForetPinceau.setVisible(false);
        rbcMaisonPinceau.setVisible(false);
        rbcEauPinceau.setVisible(false);
        rbcTerrePinceau.setVisible(false);

        bReset.setVisible(false);
        
        bMapDessin.setVisible(false);
        
        
    }

    //getter and setter
    public MyButton getbMapDessin() {
        return bMapDessin;
    }

    public MyButton getbReset() {
        return bReset;
    }

    public JLabel getlEpaisseur() {
        return lEpaisseur;
    }

    public JLabel getlPinceau() {
        return lPinceau;
    }

    public RadioButtonCustom getRbcEauPinceau() {
        return rbcEauPinceau;
    }

    public RadioButtonCustom getRbcEauToile() {
        return rbcEauToile;
    }

    public RadioButtonCustom getRbcForetPinceau() {
        return rbcForetPinceau;
    }

    public RadioButtonCustom getRbcForetToile() {
        return rbcForetToile;
    }

    public RadioButtonCustom getRbcMaisonPinceau() {
        return rbcMaisonPinceau;
    }

    public RadioButtonCustom getRbcMaisonToile() {
        return rbcMaisonToile;
    }

    public RadioButtonCustom getRbcPrairiePinceau() {
        return rbcPrairiePinceau;
    }

    public RadioButtonCustom getRbcPrairieToile() {
        return rbcPrairieToile;
    }

    public RadioButtonCustom getRbcTerrePinceau() {
        return rbcTerrePinceau;
    }

    public RadioButtonCustom getRbcTerreToile() {
        return rbcTerreToile;
    }

    public JsliderCustom_Epaisseur getScEpaisseur() {
        return scEpaisseur;
    }

    public ButtonGroup getBgPinceau() {
        return bgPinceau;
    }

    public ButtonGroup getBgToile() {
        return bgToile;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPinceau = new javax.swing.ButtonGroup();
        bgToile = new javax.swing.ButtonGroup();
        lTitre = new javax.swing.JLabel();
        bMapDessin = new pComponents.button.MyButton();
        bReset = new pComponents.button.MyButton();
        rbcPrairiePinceau = new pComponents.radio_button.RadioButtonCustom();
        rbcForetPinceau = new pComponents.radio_button.RadioButtonCustom();
        rbcMaisonPinceau = new pComponents.radio_button.RadioButtonCustom();
        lPinceau = new javax.swing.JLabel();
        lEpaisseur = new javax.swing.JLabel();
        rbcEauPinceau = new pComponents.radio_button.RadioButtonCustom();
        rbcTerrePinceau = new pComponents.radio_button.RadioButtonCustom();
        rbcPrairieToile = new pComponents.radio_button.RadioButtonCustom();
        rbcEauToile = new pComponents.radio_button.RadioButtonCustom();
        rbcForetToile = new pComponents.radio_button.RadioButtonCustom();
        rbcTerreToile = new pComponents.radio_button.RadioButtonCustom();
        rbcMaisonToile = new pComponents.radio_button.RadioButtonCustom();
        lToile = new javax.swing.JLabel();
        scEpaisseur = new pComponents.slider_material.JsliderCustom_Epaisseur();

        setBackground(new java.awt.Color(60, 68, 115));
        setPreferredSize(new java.awt.Dimension(447, 599));

        lTitre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lTitre.setForeground(new java.awt.Color(255, 255, 255));
        lTitre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTitre.setText("Dessiner votre terrain");
        lTitre.setPreferredSize(new java.awt.Dimension(309, 16));

        bMapDessin.setBackground(new java.awt.Color(242, 113, 65));
        bMapDessin.setForeground(new java.awt.Color(255, 255, 255));
        bMapDessin.setText("Génération de la carte dessinée");
        bMapDessin.setBorderColor(new java.awt.Color(242, 113, 65));
        bMapDessin.setColor(new java.awt.Color(242, 113, 65));
        bMapDessin.setColorClick(new java.awt.Color(222, 93, 45));
        bMapDessin.setColorOver(new java.awt.Color(242, 113, 65));
        bMapDessin.setMaximumSize(new java.awt.Dimension(316, 30));
        bMapDessin.setMinimumSize(new java.awt.Dimension(316, 30));
        bMapDessin.setPreferredSize(new java.awt.Dimension(309, 40));
        bMapDessin.setRadius(50);

        bReset.setBackground(new java.awt.Color(242, 113, 65));
        bReset.setForeground(new java.awt.Color(255, 255, 255));
        bReset.setText("Nouvelle Toile");
        bReset.setBorderColor(new java.awt.Color(242, 113, 65));
        bReset.setColor(new java.awt.Color(242, 113, 65));
        bReset.setColorClick(new java.awt.Color(222, 93, 45));
        bReset.setColorOver(new java.awt.Color(242, 113, 65));
        bReset.setMaximumSize(new java.awt.Dimension(316, 42));
        bReset.setMinimumSize(new java.awt.Dimension(316, 42));
        bReset.setPreferredSize(new java.awt.Dimension(148, 40));
        bReset.setRadius(50);

        rbcPrairiePinceau.setBackground(new java.awt.Color(242, 143, 56));
        bgPinceau.add(rbcPrairiePinceau);
        rbcPrairiePinceau.setForeground(new java.awt.Color(255, 255, 255));
        rbcPrairiePinceau.setText("Prairie");
        rbcPrairiePinceau.setPreferredSize(new java.awt.Dimension(145, 20));

        rbcForetPinceau.setBackground(new java.awt.Color(242, 143, 56));
        bgPinceau.add(rbcForetPinceau);
        rbcForetPinceau.setForeground(new java.awt.Color(255, 255, 255));
        rbcForetPinceau.setText("Forêt");
        rbcForetPinceau.setPreferredSize(new java.awt.Dimension(145, 20));

        rbcMaisonPinceau.setBackground(new java.awt.Color(242, 143, 56));
        bgPinceau.add(rbcMaisonPinceau);
        rbcMaisonPinceau.setForeground(new java.awt.Color(255, 255, 255));
        rbcMaisonPinceau.setText("Maison");
        rbcMaisonPinceau.setPreferredSize(new java.awt.Dimension(145, 20));

        lPinceau.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lPinceau.setForeground(new java.awt.Color(255, 255, 255));
        lPinceau.setText("Sélectionner le type de terrain pour le pinceau");
        lPinceau.setPreferredSize(new java.awt.Dimension(309, 16));

        lEpaisseur.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lEpaisseur.setForeground(new java.awt.Color(255, 255, 255));
        lEpaisseur.setText("Sélectionner l'épaisseur du pinceau ");
        lEpaisseur.setPreferredSize(new java.awt.Dimension(309, 16));

        rbcEauPinceau.setBackground(new java.awt.Color(242, 143, 56));
        bgPinceau.add(rbcEauPinceau);
        rbcEauPinceau.setForeground(new java.awt.Color(255, 255, 255));
        rbcEauPinceau.setText("Eau");
        rbcEauPinceau.setPreferredSize(new java.awt.Dimension(145, 20));

        rbcTerrePinceau.setBackground(new java.awt.Color(242, 143, 56));
        bgPinceau.add(rbcTerrePinceau);
        rbcTerrePinceau.setForeground(new java.awt.Color(255, 255, 255));
        rbcTerrePinceau.setText("Terre");
        rbcTerrePinceau.setPreferredSize(new java.awt.Dimension(145, 20));

        rbcPrairieToile.setBackground(new java.awt.Color(242, 113, 65));
        bgToile.add(rbcPrairieToile);
        rbcPrairieToile.setForeground(new java.awt.Color(255, 255, 255));
        rbcPrairieToile.setText("Prairie");
        rbcPrairieToile.setPreferredSize(new java.awt.Dimension(145, 20));

        rbcEauToile.setBackground(new java.awt.Color(242, 113, 65));
        bgToile.add(rbcEauToile);
        rbcEauToile.setForeground(new java.awt.Color(255, 255, 255));
        rbcEauToile.setText("Eau");
        rbcEauToile.setPreferredSize(new java.awt.Dimension(145, 20));

        rbcForetToile.setBackground(new java.awt.Color(242, 113, 65));
        bgToile.add(rbcForetToile);
        rbcForetToile.setForeground(new java.awt.Color(255, 255, 255));
        rbcForetToile.setText("Forêt");
        rbcForetToile.setPreferredSize(new java.awt.Dimension(145, 20));

        rbcTerreToile.setBackground(new java.awt.Color(242, 113, 65));
        bgToile.add(rbcTerreToile);
        rbcTerreToile.setForeground(new java.awt.Color(255, 255, 255));
        rbcTerreToile.setText("Terre");
        rbcTerreToile.setPreferredSize(new java.awt.Dimension(145, 20));

        rbcMaisonToile.setBackground(new java.awt.Color(242, 113, 65));
        bgToile.add(rbcMaisonToile);
        rbcMaisonToile.setForeground(new java.awt.Color(255, 255, 255));
        rbcMaisonToile.setText("Maison");
        rbcMaisonToile.setPreferredSize(new java.awt.Dimension(145, 20));

        lToile.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lToile.setForeground(new java.awt.Color(255, 255, 255));
        lToile.setText("Sélectionner le type de terrain pour la toile");
        lToile.setPreferredSize(new java.awt.Dimension(309, 16));

        scEpaisseur.setBackground(new java.awt.Color(191, 94, 94));
        scEpaisseur.setForeground(new java.awt.Color(191, 94, 94));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scEpaisseur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbcPrairiePinceau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbcMaisonPinceau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbcForetPinceau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rbcEauPinceau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbcTerrePinceau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bMapDessin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lTitre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lPinceau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(166, 166, 166)
                                .addComponent(bReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lEpaisseur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbcPrairieToile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rbcMaisonToile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rbcForetToile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(rbcEauToile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rbcTerreToile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lToile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(lToile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbcEauToile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbcPrairieToile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbcForetToile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbcTerreToile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbcMaisonToile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(lEpaisseur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scEpaisseur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lPinceau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbcEauPinceau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbcPrairiePinceau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbcForetPinceau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbcTerrePinceau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbcMaisonPinceau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(bReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(bMapDessin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
    }// </editor-fold>//GEN-END:initComponents

    //methodes d'action
    public void addSelectionFond(ActionListener evt) {          //creation methode qui met a l'ecoute ces composants 
        rbcTerreToile.addActionListener(evt);                   //pour recuperer leurs valeur dans le fichier pDessin
        rbcEauToile.addActionListener(evt);
        rbcForetToile.addActionListener(evt);
        rbcMaisonToile.addActionListener(evt);
        rbcPrairieToile.addActionListener(evt);
    }

    public void addEpaisseur(MouseListener evt) {          //creation methode qui met a l'ecoute ces composants 
        scEpaisseur.addMouseListener(evt);                 //pour recuperer leurs valeur dans le fichier pDessin
    }
    
    public void addPinceau(ActionListener evt) {          //creation methode qui met a l'ecoute ces composants 
        rbcTerrePinceau.addActionListener(evt);           //pour recuperer leurs valeur dans le fichier pDessin
        rbcEauPinceau.addActionListener(evt);
        rbcForetPinceau.addActionListener(evt);
        rbcMaisonPinceau.addActionListener(evt);
        rbcPrairiePinceau.addActionListener(evt);
    }
    
    public void addReset(ActionListener evt) {          //creation methode qui met a l'ecoute ces composants 
        bReset.addActionListener(evt);                  //pour recuperer leurs valeur dans le fichier pDessin
    }
    
    public void addGenererMapDessin(ActionListener evt) {         //creation methode qui met a l'ecoute ces composants 
        bMapDessin.addActionListener(evt);                        //pour recuperer leurs valeur dans le fichier pDessin
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pComponents.button.MyButton bMapDessin;
    private pComponents.button.MyButton bReset;
    private javax.swing.ButtonGroup bgPinceau;
    private javax.swing.ButtonGroup bgToile;
    private javax.swing.JLabel lEpaisseur;
    private javax.swing.JLabel lPinceau;
    private javax.swing.JLabel lTitre;
    private javax.swing.JLabel lToile;
    private pComponents.radio_button.RadioButtonCustom rbcEauPinceau;
    private pComponents.radio_button.RadioButtonCustom rbcEauToile;
    private pComponents.radio_button.RadioButtonCustom rbcForetPinceau;
    private pComponents.radio_button.RadioButtonCustom rbcForetToile;
    private pComponents.radio_button.RadioButtonCustom rbcMaisonPinceau;
    private pComponents.radio_button.RadioButtonCustom rbcMaisonToile;
    private pComponents.radio_button.RadioButtonCustom rbcPrairiePinceau;
    private pComponents.radio_button.RadioButtonCustom rbcPrairieToile;
    private pComponents.radio_button.RadioButtonCustom rbcTerrePinceau;
    private pComponents.radio_button.RadioButtonCustom rbcTerreToile;
    private pComponents.slider_material.JsliderCustom_Epaisseur scEpaisseur;
    // End of variables declaration//GEN-END:variables
}
