/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pGeneration;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javax.swing.ButtonGroup;
import javax.swing.JLabel;
import pComponents.button.MyButton;
import pComponents.combobox.Combobox;
import pComponents.radio_button.RadioButtonCustom;
import pComponents.slider_material.JsliderCustom_Densite;

/**
 *
 * @author Think
 */
public class pParametreTerrain extends javax.swing.JPanel {

    /**
     * Creates new form pParametreTerrain
     */
    public pParametreTerrain() {
        initComponents();
        bChangement.setVisible(false);
        scDensite.setVisible(false);
        lDensite.setVisible(false);
        bParametres.setVisible(false);
        bCheminArret.setVisible(false);
        bCheminDebut.setVisible(false);
        lSurcharge.setVisible(false);
        bCheminAnnul1.setVisible(false);
        rbcChemin1.setVisible(false);
        rbcChemin2.setVisible(false);
        rbcChemin3.setVisible(false);
        lEpaisseurChemin.setVisible(false);
        
    }

    //getter and setter
    public JsliderCustom_Densite getScDensite() {
        return scDensite;
    }

    public Combobox getCbTailleCarte() {
        return cbTailleCarte;
    }

    public void setCbTailleCarte(Combobox cbTailleCarte) {
        this.cbTailleCarte = cbTailleCarte;
    }

    public void setScDensite(JsliderCustom_Densite scDensite) {
        this.scDensite = scDensite;
    }

    public MyButton getbChangement() {
        return bChangement;
    }

    public JLabel getlDensite() {
        return lDensite;
    }

    public MyButton getbParametres() {
        return bParametres;
    }

    public MyButton getbSurchargeArret() {
        return bCheminArret;
    }

    public MyButton getbSurchargeDebut() {
        return bCheminDebut;
    }

    public JLabel getlSurcharge() {
        return lSurcharge;
    }

    public MyButton getbCheminAnnul() {
        return bCheminAnnul1;
    }

    public JLabel getlEpaisseurChemin() {
        return lEpaisseurChemin;
    }

    public RadioButtonCustom getRbcChemin1() {
        return rbcChemin1;
    }

    public RadioButtonCustom getRbcChemin2() {
        return rbcChemin2;
    }

    public RadioButtonCustom getRbcChemin3() {
        return rbcChemin3;
    }

    public ButtonGroup getBgTailleChemin() {
        return bgTailleChemin;
    }
    
    
    
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgTailleChemin = new javax.swing.ButtonGroup();
        bChangement = new pComponents.button.MyButton();
        cbTailleCarte = new pComponents.combobox.Combobox();
        lDensite = new javax.swing.JLabel();
        bParametres = new pComponents.button.MyButton();
        scDensite = new pComponents.slider_material.JsliderCustom_Densite();
        bCheminDebut = new pComponents.button.MyButton();
        bCheminArret = new pComponents.button.MyButton();
        lSurcharge = new javax.swing.JLabel();
        bCheminAnnul1 = new pComponents.button.MyButton();
        rbcChemin1 = new pComponents.radio_button.RadioButtonCustom();
        rbcChemin2 = new pComponents.radio_button.RadioButtonCustom();
        rbcChemin3 = new pComponents.radio_button.RadioButtonCustom();
        lEpaisseurChemin = new javax.swing.JLabel();

        setBackground(new java.awt.Color(60, 68, 115));
        setPreferredSize(new java.awt.Dimension(447, 599));

        bChangement.setBackground(new java.awt.Color(242, 143, 56));
        bChangement.setForeground(new java.awt.Color(255, 255, 255));
        bChangement.setText("Changement de Carte");
        bChangement.setBorderColor(new java.awt.Color(242, 143, 56));
        bChangement.setColor(new java.awt.Color(242, 143, 56));
        bChangement.setColorClick(new java.awt.Color(222, 123, 36));
        bChangement.setColorOver(new java.awt.Color(242, 143, 56));
        bChangement.setMaximumSize(new java.awt.Dimension(316, 42));
        bChangement.setMinimumSize(new java.awt.Dimension(316, 42));
        bChangement.setPreferredSize(new java.awt.Dimension(309, 40));
        bChangement.setRadius(50);

        cbTailleCarte.setBackground(new java.awt.Color(191, 94, 94));
        cbTailleCarte.setForeground(new java.awt.Color(255, 255, 255));
        cbTailleCarte.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "8 x 8", "16 x 16", "32 x 32", "64 x 64", "128 x 128", "256 x 256", "512 x 512" }));
        cbTailleCarte.setSelectedIndex(-1);
        cbTailleCarte.setToolTipText("");
        cbTailleCarte.setMaximumSize(new java.awt.Dimension(311, 50));
        cbTailleCarte.setMinimumSize(new java.awt.Dimension(311, 50));
        cbTailleCarte.setPreferredSize(new java.awt.Dimension(309, 50));
        cbTailleCarte.setLabeText("Entrer la taille du terrain");

        lDensite.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lDensite.setForeground(new java.awt.Color(255, 255, 255));
        lDensite.setText("Entrer la densité de végétation");
        lDensite.setPreferredSize(new java.awt.Dimension(309, 16));

        bParametres.setBackground(new java.awt.Color(191, 94, 94));
        bParametres.setForeground(new java.awt.Color(255, 255, 255));
        bParametres.setText("Parametres de simulation");
        bParametres.setBorderColor(new java.awt.Color(191, 94, 94));
        bParametres.setColor(new java.awt.Color(191, 94, 94));
        bParametres.setColorClick(new java.awt.Color(171, 74, 74));
        bParametres.setColorOver(new java.awt.Color(191, 94, 94));
        bParametres.setMaximumSize(new java.awt.Dimension(316, 30));
        bParametres.setMinimumSize(new java.awt.Dimension(316, 30));
        bParametres.setPreferredSize(new java.awt.Dimension(309, 40));
        bParametres.setRadius(50);

        scDensite.setBackground(new java.awt.Color(242, 113, 65));
        scDensite.setForeground(new java.awt.Color(242, 113, 65));
        scDensite.setPreferredSize(new java.awt.Dimension(309, 15));

        bCheminDebut.setBackground(new java.awt.Color(242, 143, 56));
        bCheminDebut.setForeground(new java.awt.Color(255, 255, 255));
        bCheminDebut.setText("Création du chemin");
        bCheminDebut.setBorderColor(new java.awt.Color(242, 143, 56));
        bCheminDebut.setColor(new java.awt.Color(242, 143, 56));
        bCheminDebut.setColorClick(new java.awt.Color(222, 123, 36));
        bCheminDebut.setColorOver(new java.awt.Color(242, 143, 56));
        bCheminDebut.setMaximumSize(new java.awt.Dimension(316, 42));
        bCheminDebut.setMinimumSize(new java.awt.Dimension(316, 42));
        bCheminDebut.setPreferredSize(new java.awt.Dimension(309, 40));
        bCheminDebut.setRadius(50);
        bCheminDebut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCheminDebutActionPerformed(evt);
            }
        });

        bCheminArret.setBackground(new java.awt.Color(242, 113, 65));
        bCheminArret.setForeground(new java.awt.Color(255, 255, 255));
        bCheminArret.setText("Arrêt du chemin");
        bCheminArret.setBorderColor(new java.awt.Color(242, 113, 65));
        bCheminArret.setColor(new java.awt.Color(242, 113, 65));
        bCheminArret.setColorClick(new java.awt.Color(222, 93, 45));
        bCheminArret.setColorOver(new java.awt.Color(242, 113, 65));
        bCheminArret.setMaximumSize(new java.awt.Dimension(316, 42));
        bCheminArret.setMinimumSize(new java.awt.Dimension(316, 42));
        bCheminArret.setPreferredSize(new java.awt.Dimension(148, 40));
        bCheminArret.setRadius(50);

        lSurcharge.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lSurcharge.setForeground(new java.awt.Color(255, 255, 255));
        lSurcharge.setText(" ");

        bCheminAnnul1.setBackground(new java.awt.Color(242, 113, 65));
        bCheminAnnul1.setForeground(new java.awt.Color(255, 255, 255));
        bCheminAnnul1.setText("Annulation du chemin");
        bCheminAnnul1.setBorderColor(new java.awt.Color(242, 113, 65));
        bCheminAnnul1.setColor(new java.awt.Color(242, 113, 65));
        bCheminAnnul1.setColorClick(new java.awt.Color(222, 93, 45));
        bCheminAnnul1.setColorOver(new java.awt.Color(242, 113, 65));
        bCheminAnnul1.setMaximumSize(new java.awt.Dimension(316, 42));
        bCheminAnnul1.setMinimumSize(new java.awt.Dimension(316, 42));
        bCheminAnnul1.setPreferredSize(new java.awt.Dimension(148, 40));
        bCheminAnnul1.setRadius(50);

        rbcChemin1.setBackground(new java.awt.Color(242, 113, 65));
        bgTailleChemin.add(rbcChemin1);
        rbcChemin1.setForeground(new java.awt.Color(255, 255, 255));
        rbcChemin1.setText("Epaisseur chemin : 1");
        rbcChemin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbcChemin1ActionPerformed(evt);
            }
        });

        rbcChemin2.setBackground(new java.awt.Color(242, 113, 65));
        bgTailleChemin.add(rbcChemin2);
        rbcChemin2.setForeground(new java.awt.Color(255, 255, 255));
        rbcChemin2.setText("Epaisseur chemin : 2");

        rbcChemin3.setBackground(new java.awt.Color(242, 113, 65));
        bgTailleChemin.add(rbcChemin3);
        rbcChemin3.setForeground(new java.awt.Color(255, 255, 255));
        rbcChemin3.setText("Epaisseur chemin : 3");

        lEpaisseurChemin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lEpaisseurChemin.setForeground(new java.awt.Color(255, 255, 255));
        lEpaisseurChemin.setText("Entrer l'épaisseur du chemin souhaité");
        lEpaisseurChemin.setPreferredSize(new java.awt.Dimension(309, 16));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbcChemin3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbcChemin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbcChemin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bParametres, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                            .addComponent(bCheminDebut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bChangement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lDensite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(scDensite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lEpaisseurChemin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lSurcharge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bCheminArret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bCheminAnnul1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbTailleCarte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(cbTailleCarte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(lDensite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scDensite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(bChangement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(bCheminDebut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lEpaisseurChemin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbcChemin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbcChemin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbcChemin3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lSurcharge)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCheminArret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCheminAnnul1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bParametres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bCheminDebutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCheminDebutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bCheminDebutActionPerformed

    private void rbcChemin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbcChemin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbcChemin1ActionPerformed

    //methodes d'action
    public void addSelectionDensite(MouseListener evt) {
        scDensite.addMouseListener(evt);
    }
    
    public void addSelectionTaille(ActionListener evt) {
        cbTailleCarte.addActionListener(evt);
    }
    
    public void addSelectionChangement(ActionListener evt) {
        bChangement.addActionListener(evt);
    }
    
    public void addParametresSimu(ActionListener evt) {
        bParametres.addActionListener(evt);
    }
    
    public void addSurchargeDebut(ActionListener evt) {
        bCheminDebut.addActionListener(evt);
    }
    
    public void addSurchargeArret(ActionListener evt) {
        bCheminArret.addActionListener(evt);
    }
    
    public void addSurchargeAnnul(ActionListener evt) {
        bCheminAnnul1.addActionListener(evt);
    }
    
    public void addEpaisseurChemin(ActionListener evt) {
        rbcChemin1.addActionListener(evt);
        rbcChemin2.addActionListener(evt);
        rbcChemin3.addActionListener(evt);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pComponents.button.MyButton bChangement;
    private pComponents.button.MyButton bCheminAnnul1;
    private pComponents.button.MyButton bCheminArret;
    private pComponents.button.MyButton bCheminDebut;
    private pComponents.button.MyButton bParametres;
    private javax.swing.ButtonGroup bgTailleChemin;
    private pComponents.combobox.Combobox cbTailleCarte;
    private javax.swing.JLabel lDensite;
    private javax.swing.JLabel lEpaisseurChemin;
    private javax.swing.JLabel lSurcharge;
    private pComponents.radio_button.RadioButtonCustom rbcChemin1;
    private pComponents.radio_button.RadioButtonCustom rbcChemin2;
    private pComponents.radio_button.RadioButtonCustom rbcChemin3;
    private pComponents.slider_material.JsliderCustom_Densite scDensite;
    // End of variables declaration//GEN-END:variables
}
