/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pGeneration;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javax.swing.JLabel;
import pComponents.button.MyButton;
import pComponents.circularSlider.CustomSlider;
import pComponents.combobox.Combobox;
import pComponents.slider_material.JsliderCustom_feu;
import pComponents.slider_material.JsliderCustom_humidite;

/**
 *
 * @author Think
 */
public class pParametreMeteo extends javax.swing.JPanel {

    /**
     * Creates new form pParametreMeteo
     */
    public pParametreMeteo() {
        initComponents();
        this.lOrientation.setVisible(false);
        this.CSVent.setVisible(false);
        this.lhumidite.setVisible(false);
        this.scHumidite.setVisible(false);
        this.lDepartManuel.setVisible(false);
        this.scFeu.setVisible(false);
        this.bFeuAleatoire.setVisible(false);
        this.bFeuManuel.setVisible(false);
        this.lfeu.setVisible(false);
        this.bSimulation.setVisible(false);
    }


    //Getter and Setter
    public MyButton getbSimulation() {
        return bSimulation;
    }

    public void setlChoixFeu(JLabel lChoixFeu) {
        this.lDepartManuel = lChoixFeu;
    }
    
    public JLabel getlChoixFeu() {
        return lDepartManuel;
    }

    public CustomSlider getCSVent() {
        return CSVent;
    }

    public MyButton getbFeuAleatoire() {
        return bFeuAleatoire;
    }

    public MyButton getbFeuManuel() {
        return bFeuManuel;
    }

    public Combobox getCbForceVent() {
        return cbForceVent;
    }

    public JLabel getlOrientation() {
        return lOrientation;
    }

    public JLabel getLfeu() {
        return lfeu;
    }

    public JLabel getLhumidite() {
        return lhumidite;
    }

    public JsliderCustom_feu getScFeu() {
        return scFeu;
    }

    public JsliderCustom_humidite getScHumidite() {
        return scHumidite;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CSVent = new pComponents.circularSlider.CustomSlider();
        lhumidite = new javax.swing.JLabel();
        lfeu = new javax.swing.JLabel();
        bFeuAleatoire = new pComponents.button.MyButton();
        bFeuManuel = new pComponents.button.MyButton();
        scHumidite = new pComponents.slider_material.JsliderCustom_humidite();
        scFeu = new pComponents.slider_material.JsliderCustom_feu();
        lDepartManuel = new javax.swing.JLabel();
        bSimulation = new pComponents.button.MyButton();
        cbForceVent = new pComponents.combobox.Combobox();
        lOrientation = new javax.swing.JLabel();

        setBackground(new java.awt.Color(60, 68, 115));
        setPreferredSize(new java.awt.Dimension(447, 599));

        CSVent.setForeground(new java.awt.Color(255, 255, 255));
        CSVent.setOpaque(false);

        javax.swing.GroupLayout CSVentLayout = new javax.swing.GroupLayout(CSVent);
        CSVent.setLayout(CSVentLayout);
        CSVentLayout.setHorizontalGroup(
            CSVentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        CSVentLayout.setVerticalGroup(
            CSVentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );

        lhumidite.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lhumidite.setForeground(new java.awt.Color(255, 255, 255));
        lhumidite.setText("Entrer le pourcentage d'humidité");
        lhumidite.setPreferredSize(new java.awt.Dimension(309, 16));

        lfeu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lfeu.setForeground(new java.awt.Color(255, 255, 255));
        lfeu.setText("Entrer le nombre de départs de feux");
        lfeu.setPreferredSize(new java.awt.Dimension(309, 16));

        bFeuAleatoire.setBorder(null);
        bFeuAleatoire.setForeground(new java.awt.Color(255, 255, 255));
        bFeuAleatoire.setText("Départs de feux aléatoires");
        bFeuAleatoire.setBorderColor(new java.awt.Color(242, 143, 56));
        bFeuAleatoire.setColor(new java.awt.Color(242, 143, 56));
        bFeuAleatoire.setColorClick(new java.awt.Color(222, 123, 36));
        bFeuAleatoire.setColorOver(new java.awt.Color(242, 143, 56));
        bFeuAleatoire.setPreferredSize(new java.awt.Dimension(309, 40));
        bFeuAleatoire.setRadius(50);
        bFeuAleatoire.setRequestFocusEnabled(false);

        bFeuManuel.setBackground(new java.awt.Color(242, 113, 65));
        bFeuManuel.setBorder(null);
        bFeuManuel.setForeground(new java.awt.Color(255, 255, 255));
        bFeuManuel.setText("Départ de feux Manuels");
        bFeuManuel.setBorderColor(new java.awt.Color(242, 113, 65));
        bFeuManuel.setColor(new java.awt.Color(242, 113, 65));
        bFeuManuel.setColorClick(new java.awt.Color(222, 93, 45));
        bFeuManuel.setColorOver(new java.awt.Color(242, 113, 65));
        bFeuManuel.setMaximumSize(new java.awt.Dimension(316, 30));
        bFeuManuel.setMinimumSize(new java.awt.Dimension(316, 30));
        bFeuManuel.setPreferredSize(new java.awt.Dimension(309, 40));
        bFeuManuel.setRadius(50);
        bFeuManuel.setRequestFocusEnabled(false);

        scHumidite.setBackground(new java.awt.Color(242, 113, 65));
        scHumidite.setForeground(new java.awt.Color(242, 113, 65));
        scHumidite.setPreferredSize(new java.awt.Dimension(309, 15));

        scFeu.setBackground(new java.awt.Color(242, 143, 56));
        scFeu.setForeground(new java.awt.Color(242, 143, 56));
        scFeu.setPreferredSize(new java.awt.Dimension(309, 15));

        lDepartManuel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lDepartManuel.setForeground(new java.awt.Color(255, 255, 255));
        lDepartManuel.setText(" ");

        bSimulation.setBackground(new java.awt.Color(191, 94, 94));
        bSimulation.setBorder(null);
        bSimulation.setForeground(new java.awt.Color(255, 255, 255));
        bSimulation.setText("Lancer la Simulation");
        bSimulation.setBorderColor(new java.awt.Color(191, 94, 94));
        bSimulation.setColor(new java.awt.Color(191, 94, 94));
        bSimulation.setColorClick(new java.awt.Color(171, 74, 74));
        bSimulation.setColorOver(new java.awt.Color(191, 94, 94));
        bSimulation.setMaximumSize(new java.awt.Dimension(316, 30));
        bSimulation.setMinimumSize(new java.awt.Dimension(316, 30));
        bSimulation.setPreferredSize(new java.awt.Dimension(309, 40));
        bSimulation.setRadius(50);
        bSimulation.setRequestFocusEnabled(false);

        cbForceVent.setBackground(new java.awt.Color(191, 94, 94));
        cbForceVent.setForeground(new java.awt.Color(255, 255, 255));
        cbForceVent.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Vent nul", "Vent faible", "Vent modéré", "Vent fort" }));
        cbForceVent.setSelectedIndex(-1);
        cbForceVent.setToolTipText("");
        cbForceVent.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbForceVent.setLabeText("Entrer la force du vent");
        cbForceVent.setMaximumSize(new java.awt.Dimension(311, 50));
        cbForceVent.setMinimumSize(new java.awt.Dimension(311, 50));
        cbForceVent.setName("Entrer la force du ven"); // NOI18N
        cbForceVent.setPreferredSize(new java.awt.Dimension(309, 50));

        lOrientation.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lOrientation.setForeground(new java.awt.Color(255, 255, 255));
        lOrientation.setText("Entrer l'orientation du vent");
        lOrientation.setPreferredSize(new java.awt.Dimension(309, 16));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lDepartManuel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cbForceVent, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lOrientation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(7, 7, 7))
                    .addComponent(scHumidite, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lhumidite, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lfeu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bFeuAleatoire, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scFeu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bFeuManuel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bSimulation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addComponent(CSVent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbForceVent, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lOrientation, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CSVent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lhumidite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scHumidite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lfeu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scFeu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(bFeuAleatoire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bFeuManuel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lDepartManuel)
                .addGap(12, 12, 12)
                .addComponent(bSimulation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    //methodes d'action
    public void addSelectionForceVent(ActionListener evt) {
        cbForceVent.addActionListener(evt);
    }
    
    public void addSelectionOrientationVent(MouseListener evt) {
        CSVent.addMouseListener(evt);
    }
    
    public void addSelectionHumidite(MouseListener evt) {
        scHumidite.addMouseListener(evt);
    }
    
    public void addSelectionNbFeu(MouseListener evt) {
        scFeu.addMouseListener(evt);
    }
    
    public void addFeuAleatoire(ActionListener evt) {
        bFeuAleatoire.addActionListener(evt);
    }
    
    public void addFeuManuel(ActionListener evt) {
        bFeuManuel.addActionListener(evt);
    }
    
    public void addSimulation(ActionListener evt) {
        bSimulation.addActionListener(evt);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pComponents.circularSlider.CustomSlider CSVent;
    private pComponents.button.MyButton bFeuAleatoire;
    private pComponents.button.MyButton bFeuManuel;
    private pComponents.button.MyButton bSimulation;
    private pComponents.combobox.Combobox cbForceVent;
    private javax.swing.JLabel lDepartManuel;
    private javax.swing.JLabel lOrientation;
    private javax.swing.JLabel lfeu;
    private javax.swing.JLabel lhumidite;
    private pComponents.slider_material.JsliderCustom_feu scFeu;
    private pComponents.slider_material.JsliderCustom_humidite scHumidite;
    // End of variables declaration//GEN-END:variables
}
